artifact_uri: file:///C:/Users/Jay/OneDrive/Documents/Project%20exhibition/Heart-Disease-Prediction/.mlflow/0/6eac52c2d16e4364b316606a1ba6e941/artifacts
end_time: 1790714590525
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6eac52c2d16e4364b316606a1ba6e941
run_name: enthused-newt-324
run_uuid: 6eac52c2d16e4364b316606a1ba6e941
source_name: ''
source_type: 4
source_version: ''
start_time: 1790714583973
status: 3
tags: []
user_id: Jay
